### ISSUE TITLE
Getting an error while sending a email

### ISSUE THREAD

**Issue by yaswanthkata** [yuva2811/bookmyshow_tickets_notifier#3]
![image](https://cloud.githubusercontent.com/assets/3971157/25375653/ff59e8a6-29be-11e7-9a77-6c1d4a5837c4.png)

**Comment by ykakarap** [comment]
@yashwanthkata I was not able to reproduce this. Please check if the gmail id and password you are using are valid.

**Comment by ykakarap** [comment]
@yashwanthkata I was able to reproduce it after i ran the script on AWS EC2. I believe you might also be doing something similar. Looks like AWS EC2 has strict firewall settings to limit inbound/outbound SMTP calls. To solve that you can use AWS SES. I tested it and it works.

**Comment by yaswanthkata** [comment]
Yeah working fine after changing the settings in google app.Thanks
